// UILayout.js — the game's UI layout: every HUD element, placed and styled in the editor (UI tab).
// The editor rewrites the whole file (POST /api/save-ui) — keep the format. Drawn by js/UI.js;
// game code takes an element by id: UI.get('score').setText('10') — and never positions HUD itself.
//   kind — 'text' | 'panel' | 'bar' | 'button'; anchor — one of 9 screen points ('top-left' …
//   'bottom-right'): x, y go from it to the same point of the element (inward from an edge,
//   signed from the center); w, h — px; numbers are px of a screen UI_REF_HEIGHT tall;
//   parent (optional) — id of the element this one sits in: anchor, x, y then count from the
//   parent's box, the parent clips it and hides it together with itself;
//   stretch (optional) — 'h' | 'v' | 'both': fills the container on that axis, x (y) — the inset
//   from both edges, w (h) is ignored;
//   colors — '#rrggbb', '' — none; visible: 0 — hidden until the game calls show().
//   Records go in drawing order: later — on top.
const UI_LAYOUT = [
    { id: 'toolbar', kind: 'panel', anchor: 'top-left', x: 0, y: 0, w: 1280, h: 34, stretch: 'h', fill: '#23272e', border: '', radius: 0, alpha: 0.95, visible: 1 },
    { id: 'tb_pause', kind: 'button', anchor: 'top-left', parent: 'toolbar', x: 4, y: 3, w: 40, h: 28, text: "||", fontSize: 14, color: '#ffffff', fill: '#4a5a6e', border: '', radius: 4, alpha: 1, visible: 1 },
    { id: 'tb_ff', kind: 'button', anchor: 'top-left', parent: 'toolbar', x: 46, y: 3, w: 40, h: 28, text: ">>", fontSize: 14, color: '#ffffff', fill: '#4a5a6e', border: '', radius: 4, alpha: 1, visible: 1 },
    { id: 'tb_menu', kind: 'button', anchor: 'top-left', parent: 'toolbar', x: 90, y: 3, w: 52, h: 28, text: "Game", fontSize: 11, color: '#ffffff', fill: '#6e5a3a', border: '', radius: 4, alpha: 1, visible: 1 },
    { id: 'tb_towns', kind: 'button', anchor: 'top-left', parent: 'toolbar', x: 146, y: 3, w: 50, h: 28, text: "Towns", fontSize: 11, color: '#ffffff', fill: '#3e4a5a', border: '', radius: 4, alpha: 1, visible: 1 },
    { id: 'tb_subs', kind: 'button', anchor: 'top-left', parent: 'toolbar', x: 198, y: 3, w: 64, h: 28, text: "Subsidies", fontSize: 11, color: '#ffffff', fill: '#3e4a5a', border: '', radius: 4, alpha: 1, visible: 1 },
    { id: 'tb_stations', kind: 'button', anchor: 'top-left', parent: 'toolbar', x: 264, y: 3, w: 60, h: 28, text: "Stations", fontSize: 11, color: '#ffffff', fill: '#3e4a5a', border: '', radius: 4, alpha: 1, visible: 1 },
    { id: 'tb_fin', kind: 'button', anchor: 'top-left', parent: 'toolbar', x: 326, y: 3, w: 62, h: 28, text: "Finances", fontSize: 11, color: '#ffffff', fill: '#3e4a5a', border: '', radius: 4, alpha: 1, visible: 1 },
    { id: 'tb_company', kind: 'button', anchor: 'top-left', parent: 'toolbar', x: 390, y: 3, w: 62, h: 28, text: "Company", fontSize: 11, color: '#ffffff', fill: '#3e4a5a', border: '', radius: 4, alpha: 1, visible: 1 },
    { id: 'tb_ind', kind: 'button', anchor: 'top-left', parent: 'toolbar', x: 454, y: 3, w: 66, h: 28, text: "Industries", fontSize: 11, color: '#ffffff', fill: '#3e4a5a', border: '', radius: 4, alpha: 1, visible: 1 },
    { id: 'tb_trains', kind: 'button', anchor: 'top-left', parent: 'toolbar', x: 522, y: 3, w: 50, h: 28, text: "Trains", fontSize: 11, color: '#ffffff', fill: '#35505e', border: '', radius: 4, alpha: 1, visible: 1 },
    { id: 'tb_rvs', kind: 'button', anchor: 'top-left', parent: 'toolbar', x: 574, y: 3, w: 58, h: 28, text: "Road", fontSize: 11, color: '#ffffff', fill: '#35505e', border: '', radius: 4, alpha: 1, visible: 1 },
    { id: 'tb_ships', kind: 'button', anchor: 'top-left', parent: 'toolbar', x: 634, y: 3, w: 46, h: 28, text: "Ships", fontSize: 11, color: '#ffffff', fill: '#35505e', border: '', radius: 4, alpha: 1, visible: 1 },
    { id: 'tb_air', kind: 'button', anchor: 'top-left', parent: 'toolbar', x: 682, y: 3, w: 56, h: 28, text: "Aircraft", fontSize: 11, color: '#ffffff', fill: '#35505e', border: '', radius: 4, alpha: 1, visible: 1 },
    { id: 'tb_news', kind: 'button', anchor: 'top-left', parent: 'toolbar', x: 740, y: 3, w: 44, h: 28, text: "News", fontSize: 11, color: '#ffffff', fill: '#3e4a5a', border: '', radius: 4, alpha: 1, visible: 1 },
    { id: 'tb_map', kind: 'button', anchor: 'top-left', parent: 'toolbar', x: 786, y: 3, w: 40, h: 28, text: "Map", fontSize: 11, color: '#ffffff', fill: '#3e4a5a', border: '', radius: 4, alpha: 1, visible: 1 },
    { id: 'tb_query', kind: 'button', anchor: 'top-right', parent: 'toolbar', x: 4, y: 3, w: 30, h: 28, text: "?", fontSize: 14, color: '#ffffff', fill: '#4a5a6e', border: '', radius: 4, alpha: 1, visible: 1 },
    { id: 'tb_land', kind: 'button', anchor: 'top-right', parent: 'toolbar', x: 38, y: 3, w: 74, h: 28, text: "Landscape", fontSize: 11, color: '#ffffff', fill: '#4e6a3a', border: '', radius: 4, alpha: 1, visible: 1 },
    { id: 'tb_demolish', kind: 'button', anchor: 'top-right', parent: 'toolbar', x: 116, y: 3, w: 62, h: 28, text: "Demolish", fontSize: 11, color: '#ffffff', fill: '#7a3a2e', border: '', radius: 4, alpha: 1, visible: 1 },
    { id: 'tb_bair', kind: 'button', anchor: 'top-right', parent: 'toolbar', x: 182, y: 3, w: 56, h: 28, text: "Airports", fontSize: 11, color: '#ffffff', fill: '#4e6a3a', border: '', radius: 4, alpha: 1, visible: 1 },
    { id: 'tb_docks', kind: 'button', anchor: 'top-right', parent: 'toolbar', x: 242, y: 3, w: 48, h: 28, text: "Docks", fontSize: 11, color: '#ffffff', fill: '#4e6a3a', border: '', radius: 4, alpha: 1, visible: 1 },
    { id: 'tb_broad', kind: 'button', anchor: 'top-right', parent: 'toolbar', x: 294, y: 3, w: 48, h: 28, text: "Roads", fontSize: 11, color: '#ffffff', fill: '#4e6a3a', border: '', radius: 4, alpha: 1, visible: 1 },
    { id: 'tb_brail', kind: 'button', anchor: 'top-right', parent: 'toolbar', x: 346, y: 3, w: 58, h: 28, text: "Railway", fontSize: 11, color: '#ffffff', fill: '#4e6a3a', border: '', radius: 4, alpha: 1, visible: 1 },
    { id: 'buildbar', kind: 'panel', anchor: 'top-right', x: 4, y: 38, w: 560, h: 34, fill: '#2b3a2b', border: '', radius: 5, alpha: 0.95, visible: 0 },
    { id: 'bb', kind: 'button', anchor: 'top-left', parent: 'buildbar', x: 4, y: 3, w: 66, h: 28, text: "Tool", fontSize: 11, color: '#ffffff', fill: '#4e6a3a', border: '', radius: 4, alpha: 1, visible: 0 },
    { id: 'optbar', kind: 'panel', anchor: 'top-right', x: 4, y: 76, w: 560, h: 30, fill: '#2b2f36', border: '', radius: 5, alpha: 0.92, visible: 0 },
    { id: 'ob', kind: 'button', anchor: 'top-left', parent: 'optbar', x: 4, y: 3, w: 88, h: 24, text: "Option", fontSize: 11, color: '#ffffff', fill: '#4a5a6e', border: '', radius: 4, alpha: 1, visible: 0 },
    { id: 'win', kind: 'panel', anchor: 'top-left', x: 8, y: 42, w: 392, h: 600, fill: '#262a31', border: '#4a5566', radius: 6, alpha: 0.95, visible: 0 },
    { id: 'winTitle', kind: 'text', anchor: 'top-left', parent: 'win', x: 12, y: 8, text: "Window", fontSize: 15, color: '#f0e6c8', shadow: '#000000', alpha: 1, visible: 1 },
    { id: 'winClose', kind: 'button', anchor: 'top-right', parent: 'win', x: 6, y: 6, w: 26, h: 24, text: "x", fontSize: 13, color: '#ffffff', fill: '#7a3a2e', border: '', radius: 4, alpha: 1, visible: 1 },
    { id: 'winNext', kind: 'button', anchor: 'top-right', parent: 'win', x: 36, y: 6, w: 26, h: 24, text: ">", fontSize: 13, color: '#ffffff', fill: '#4a5a6e', border: '', radius: 4, alpha: 1, visible: 0 },
    { id: 'winPrev', kind: 'button', anchor: 'top-right', parent: 'win', x: 66, y: 6, w: 26, h: 24, text: "<", fontSize: 13, color: '#ffffff', fill: '#4a5a6e', border: '', radius: 4, alpha: 1, visible: 0 },
    { id: 'winText', kind: 'text', anchor: 'top-left', parent: 'win', x: 14, y: 40, text: "", fontSize: 12, color: '#e0e0e0', shadow: '', alpha: 1, visible: 1 },
    { id: 'wr', kind: 'button', anchor: 'top-left', parent: 'win', x: 8, y: 40, w: 376, h: 22, text: "Row", fontSize: 11, color: '#e8e8e8', fill: '#353b45', border: '', radius: 3, alpha: 1, visible: 0 },
    { id: 'wl', kind: 'button', anchor: 'top-left', parent: 'win', x: 8, y: 268, w: 376, h: 22, text: "Row", fontSize: 11, color: '#e8e8e8', fill: '#353b45', border: '', radius: 3, alpha: 1, visible: 0 },
    { id: 'winInfo', kind: 'text', anchor: 'top-left', parent: 'win', x: 14, y: 330, text: "", fontSize: 12, color: '#d8d8c8', shadow: '', alpha: 1, visible: 1 },
    { id: 'wb', kind: 'button', anchor: 'bottom-left', parent: 'win', x: 8, y: 8, w: 90, h: 26, text: "Action", fontSize: 11, color: '#ffffff', fill: '#4a5a6e', border: '', radius: 4, alpha: 1, visible: 0 },
    { id: 'status', kind: 'panel', anchor: 'bottom-left', x: 0, y: 0, w: 1280, h: 26, stretch: 'h', fill: '#23272e', border: '', radius: 0, alpha: 0.95, visible: 1 },
    { id: 'st_date', kind: 'text', anchor: 'middle-left', parent: 'status', x: 10, y: 0, text: "1st Jan 1941", fontSize: 13, color: '#f0e6c8', shadow: '', alpha: 1, visible: 1 },
    { id: 'st_news', kind: 'text', anchor: 'middle-center', parent: 'status', x: 0, y: 0, text: "", fontSize: 12, color: '#e0e0e0', shadow: '', alpha: 1, visible: 1 },
    { id: 'st_money', kind: 'text', anchor: 'middle-right', parent: 'status', x: 10, y: 0, text: "$0", fontSize: 13, color: '#9ae07a', shadow: '', alpha: 1, visible: 1 },
    { id: 'st_speed', kind: 'text', anchor: 'middle-left', parent: 'status', x: 150, y: 0, text: "", fontSize: 12, color: '#ffd060', shadow: '', alpha: 1, visible: 1 },
    { id: 'hover', kind: 'text', anchor: 'bottom-left', x: 10, y: 32, text: "", fontSize: 12, color: '#ffffff', shadow: '#000000', alpha: 0.95, visible: 1 },
    { id: 'costTip', kind: 'text', anchor: 'bottom-right', x: 10, y: 32, text: "", fontSize: 13, color: '#ffe080', shadow: '#000000', alpha: 1, visible: 1 },
    { id: 'moneyFloat', kind: 'text', anchor: 'top-center', x: 0, y: 0, text: "+$0", fontSize: 14, color: '#ffe040', shadow: '#000000', alpha: 1, visible: 0 },
    { id: 'fps', kind: 'text', anchor: 'bottom-right', x: 10, y: 52, text: "", fontSize: 10, color: '#ffffff', shadow: '#000000', alpha: 0.5, visible: 1 },
    { id: 'minimap', kind: 'canvas', anchor: 'bottom-right', x: 8, y: 34, w: 220, h: 220, fill: '#0c1a26', border: '#4a5566', radius: 4, alpha: 0.95, visible: 0 },
    { id: 'msg', kind: 'panel', anchor: 'top-center', x: 0, y: 96, w: 520, h: 40, fill: '#6a2020', border: '#e08060', radius: 6, alpha: 0.95, visible: 0 },
    { id: 'msgText', kind: 'text', anchor: 'middle-center', parent: 'msg', x: 0, y: 0, text: "", fontSize: 13, color: '#ffffff', shadow: '#000000', alpha: 1, visible: 1 },
    { id: 'newsBox', kind: 'panel', anchor: 'bottom-center', x: 0, y: 34, w: 560, h: 84, fill: '#e8dcc0', border: '#6a5a3a', radius: 4, alpha: 0.97, visible: 0 },
    { id: 'newsHead', kind: 'text', anchor: 'top-left', parent: 'newsBox', x: 12, y: 6, text: "NEWS", fontSize: 11, color: '#6a4a2a', shadow: '', alpha: 1, visible: 1 },
    { id: 'newsText', kind: 'text', anchor: 'top-left', parent: 'newsBox', x: 12, y: 24, text: "", fontSize: 14, color: '#202020', shadow: '', alpha: 1, visible: 1 },
    { id: 'newsGo', kind: 'button', anchor: 'bottom-right', parent: 'newsBox', x: 76, y: 6, w: 62, h: 22, text: "Go to", fontSize: 11, color: '#ffffff', fill: '#6a5a3a', border: '', radius: 3, alpha: 1, visible: 1 },
    { id: 'newsClose', kind: 'button', anchor: 'bottom-right', parent: 'newsBox', x: 8, y: 6, w: 62, h: 22, text: "Close", fontSize: 11, color: '#ffffff', fill: '#6a5a3a', border: '', radius: 3, alpha: 1, visible: 1 },
    { id: 'ngDim', kind: 'panel', anchor: 'top-left', x: 0, y: 0, w: 1280, h: 720, stretch: 'both', fill: '', border: '', radius: 0, alpha: 1, visible: 0 },
    { id: 'ngShade', kind: 'panel', anchor: 'top-left', parent: 'ngDim', x: 0, y: 0, w: 1280, h: 720, stretch: 'both', fill: '#000000', border: '', radius: 0, alpha: 0.55, visible: 1 },
    { id: 'ngPanel', kind: 'panel', anchor: 'middle-center', parent: 'ngDim', x: 0, y: 0, w: 540, h: 600, fill: '#262a31', border: '#8a7a5a', radius: 8, alpha: 1, visible: 1 },
    { id: 'ngTitle', kind: 'text', anchor: 'top-center', parent: 'ngPanel', x: 0, y: 14, text: "Transport Tycoon 3D", fontSize: 24, color: '#f0e6c8', shadow: '#000000', alpha: 1, visible: 1 },
    { id: 'ngSub', kind: 'text', anchor: 'top-center', parent: 'ngPanel', x: 0, y: 48, text: "New game", fontSize: 12, color: '#c8c0a8', shadow: '', alpha: 1, visible: 1 },
    { id: 'ng', kind: 'button', anchor: 'top-left', parent: 'ngPanel', x: 30, y: 74, w: 480, h: 26, text: "Option", fontSize: 12, color: '#ffffff', fill: '#3e4a5a', border: '', radius: 4, alpha: 1, visible: 0 },
    { id: 'ngStart', kind: 'button', anchor: 'bottom-left', parent: 'ngPanel', x: 30, y: 18, w: 150, h: 36, text: "Start new game", fontSize: 13, color: '#ffffff', fill: '#4e6a3a', border: '', radius: 5, alpha: 1, visible: 1 },
    { id: 'ngLoad', kind: 'button', anchor: 'bottom-center', parent: 'ngPanel', x: 0, y: 18, w: 150, h: 36, text: "Load saved game", fontSize: 13, color: '#ffffff', fill: '#4a5a6e', border: '', radius: 5, alpha: 1, visible: 1 },
    { id: 'ngResume', kind: 'button', anchor: 'bottom-right', parent: 'ngPanel', x: 30, y: 18, w: 150, h: 36, text: "Back to game", fontSize: 13, color: '#ffffff', fill: '#6e5a3a', border: '', radius: 5, alpha: 1, visible: 1 },
];
